language: python
python:
  - '3.6.7'

# safelist
branches:
  only:
    - staging

before_script:
  - 'pip install pipenv'
  - 'pipenv install'
  - 'pipenv shell'

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings.travis

script:
  - sudo python manage.py test