language: python
language: python
python:
  - '3.6.7'

# safelist
branches:
  only:
    - staging

before_script:
  # - pip install -r requirements.txt
  - 'pip install pipenv'
  - 'pipenv install'

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings.travis

script:
  - sudo pipenv run python manage.py test