language: python
python:
  - '3.6.7'

# safelist
branches:
  only:
    - staging

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings.travis

install:
  - make init
script:
  - make test