language: python
python:
  - '3.6.7'

# safelist
branches:
  only:
    - staging

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings.travis

before_install:
  - sudo service postgresql stop
  - sed -e 's/^port.*/port = 5433/' /etc/postgresql/10/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/10/main
  - sudo service postgresql start 10
  - sudo service postgresql status
  - sudo netstat -plunt |grep postgres

install:
  - make init
script:
  - make test