# Generated by Django 2.2.3 on 2019-07-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_product_user_product'),
        ('core', '0002_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_substitutes',
            field=models.ManyToManyField(to='search.Product'),
        ),
    ]
