# Generated by Django 2.2.3 on 2019-07-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_product_user_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fat_100g',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='salt_100g',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat_100g',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sugars_100g',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
