# Generated by Django 2.2.3 on 2019-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190722_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.BigIntegerField(),
        ),
    ]
