# Generated by Django 2.2.3 on 2019-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20190822_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
