# Generated by Django 2.2.3 on 2019-09-02 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('search', '0001_initial'), ('search', '0002_remove_product_user_product'), ('search', '0003_auto_20190722_1406'), ('search', '0004_auto_20190822_1427'), ('search', '0005_auto_20190822_1430')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=100)),
                ('brands', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('product_url', models.CharField(max_length=150, null=True)),
                ('product_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_image', models.CharField(max_length=100, null=True)),
                ('nutriscore', models.CharField(max_length=1, null=True)),
                ('stores', models.CharField(max_length=150, null=True)),
                ('quantity', models.CharField(max_length=40, null=True)),
                ('nova_groups', models.CharField(max_length=5, null=True)),
                ('categories', models.CharField(max_length=500, null=True)),
                ('substitutes', models.ManyToManyField(related_name='_product_substitutes_+', to='search.Product')),
                ('fat_100g', models.CharField(max_length=20, null=True)),
                ('salt_100g', models.CharField(max_length=20, null=True)),
                ('saturated_fat_100g', models.CharField(max_length=20, null=True)),
                ('sugars_100g', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
